version: '3.8'
services:
  s-auth-staging:
    image: ${DOCKER_USERNAME}/s-auth-staging
    env_file:
      - /root/config/s-auth-staging.env.txt
    container_name: s-auth-staging
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
