version: '3.8'
services:
  s-auth-staging:
    image: ${DOCKER_USERNAME}/s-auth-staging
    env_file:
      - /root/config/s-auth-staging.env.txt
    container_name: s-auth-staging
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - services_app-network
    volumes:
      - /root/services/firebase/firebase.config.json:/usr/src/app/firebase.config.json
      - /root/services/firebase/firebase.config.json:/usr/src/app/dist/firebase.config.json

networks:
  services_app-network:
    external: true
